### ISSUE TITLE
Could not find com.kovachcode:timePickerWithSeconds:1.0.1

### ISSUE THREAD

**Issue by PallabJunior** [SimformSolutionsPvtLtd/SSffmpegVideoOperation#11]
Followed the instruction to add this library in my Android Studio project but I am getting this error :
Could not find com.kovachcode:timePickerWithSeconds:1.0.1

Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/kovachcode/timePickerWithSeconds/1.0.1/timePickerWithSeconds-1.0.1.pom
       - https://repo.maven.apache.org/maven2/com/kovachcode/timePickerWithSeconds/1.0.1/timePickerWithSeconds-1.0.1.pom
       - https://jitpack.io/com/kovachcode/timePickerWithSeconds/1.0.1/timePickerWithSeconds-1.0.1.pom

What is the solution?

**Comment by Nirashu** [comment]
Can you please remove .gradle and .idea folder from your project directory and rebuild it with internet.

**Comment by mobile-simformsolutions** [comment]
@PallabJunior : Let us know your issue fixed or not. Also, give us a star if it's helpful to you

**Comment by ShwetaChauhan18** [comment]
@PallabJunior : Closing this issue. Let us know if you still have any issue.

**Comment by ShwetaChauhan18** [comment]
@PallabJunior : Closing this issue. Let us know if you still have any issue.
