### ISSUE TITLE
Large Size

### ISSUE THREAD

**Issue by kalasaceo** [SimformSolutionsPvtLtd/SSffmpegVideoOperation#15]
Though FFMEG libraries are pretty huge and this one is considerably way better but is their way to have minimal api for ffmpeg

**Comment by Nirashu** [comment]
Hello @kalasaceo  
you can use **"-preset"**,**"ultrafast"** in your query string.

**Comment by kalasaceo** [comment]
thanks.i helped a lot.
One more thing the video output quality is not so good,how could i change the output video resolution.

**Comment by Nirashu** [comment]
Output video resolution is depends on input and filter so update filters from query string.

**Comment by Nirashu** [comment]
Let us know your issue fixed or not. Also, give us star if it's helpful to you

**Comment by kalasaceo** [comment]
hi guys.
is their a way we can pass other activity class to the this reference in
CallBackOfQuery().callQuery(this, query, object : FFmpegCallBack {

As I have an activity which does not extend from AppCombatActivity and for some reason could not be extended.
i Tried creating empty AppCombatActivity by usimg
AppCombatActivity  x=new AppCombatActivity ()
but this results in crash as it should.
Do you have any thoughts how can i pass my activity which extends NativityActivity to use its reference as this(as in CallBackOfQuery().callQuery(this)
would really helps.

**Comment by milapchokshi-simformsolutions** [comment]
Please create new request for individual queries so that if another developer have same issue then they can get solution
