### ISSUE TITLE
Output Video have less resolution

### ISSUE THREAD

**Issue by rohitshama18** [SimformSolutionsPvtLtd/SSffmpegVideoOperation#16]
this is the best FFMPEG library i came through
Hi guys
How can we Encode video to custom resolution as the output video is less size but low resolution is big problem.
especially when text overlay over video is used.the drawn text is blurred

**Comment by Nirashu** [comment]
Hi @rohitshama18 
Output video resolution is depend on input & filter so update your input query string.

**Comment by Nirashu** [comment]
Let us know your issue fixed or not. Also, give us star if it's helpful to you

**Comment by Appuniverse304** [comment]
to get the full resolution add this "-qscale:v", "1" to your command before output video
