### ISSUE TITLE
Repace Video audio with custom music

### ISSUE THREAD

**Issue by rohitshama18** [SimformSolutionsPvtLtd/SSffmpegVideoOperation#17]
how can we replace audio in video with selected audio from device(audio as MP3 or AAC).

**Comment by Nirashu** [comment]
Use your own query command like as : "-i", "inputVideo.mp4", "-i", "audioInput.wav", "-c:v", "copy", "-map", "0:v:0", "-map", "1:a:0", "outputVideo.mp4"
this command is for replace audio from video.

**Comment by Nirashu** [comment]
Let us know your issue fixed or not. Also, give us star if it's helpful to you

**Comment by kalasaceo** [comment]
yes it worked fine

**Comment by ShwetaChauhan18** [comment]
ok, closing this issue

**Comment by sanojlawrence** [comment]
How do i remove audio track from video, 
My video has 3 embedded audio track, I wanted only a particular audio track, so how do i remove other two audio track
