### ISSUE TITLE
Image add to Video Failed

### ISSUE THREAD

**Issue by kalasaceo** [SimformSolutionsPvtLtd/SSffmpegVideoOperation#18]
the add image to video activity starts but results in 
"Conversion Failed" error.
could you see logs and provide hint what is wrong here are the logs.

2021-07-15 11:14:23.097 7073-7073/? I/SKBD: and isTosAccept false
2021-07-15 11:14:23.120 27165-27304/com.simform.videoimageeditor I/mobile-ffmpeg: Loaded mobile-ffmpeg-full-arm64-v8a-4.4-20200725.
2021-07-15 11:14:23.123 27165-27305/com.simform.videoimageeditor D/mobile-ffmpeg: Callback thread started.
2021-07-15 11:14:23.297 7073-7073/? I/SKBD: and isTosAccept false
2021-07-15 11:14:23.432 5796-5914/? D/NetworkController.MobileSignalController(0/-2): onSignalStrengthsChanged signalStrength=SignalStrength: 3 99 -3 -200 -3 -200 -1 99 2147483647 2147483647 2147483647 2147483647 0 2147483647 3 13 -107 0x1 P gsm|lte use_rsrp_and_rssnr_for_lte_level  [-128, -118, -108, -98] [-115, -105, -95, -85] level=1
2021-07-15 11:14:23.432 5796-5914/? D/NetworkController.MobileSignalController(0/-2): getMobileIconGroup(): 0
2021-07-15 11:14:23.477 27165-27304/com.simform.videoimageeditor I/mobile-ffmpeg: ffmpeg version v4.4-dev-416 Copyright (c) 2000-2020 the FFmpeg developers
      built with Android (6454773 based on r365631c2) clang version 9.0.8 (https://android.googlesource.com/toolchain/llvm-project 98c855489587874b2a325e7a516b99d838599c6f) (based on LLVM 9.0.8svn)
      configuration: --cross-prefix=aarch64-linux-android- --sysroot=/files/android-sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/linux-x86_64/sysroot --prefix=/home/taner/Projects/mobile-ffmpeg/prebuilt/android-arm64/ffmpeg --pkg-config=/usr/bin/pkg-config --enable-version3 --arch=aarch64 --cpu=armv8-a --cc=aarch64-linux-android24-clang --cxx=aarch64-linux-android24-clang++ --extra-libs='-L/home/taner/Projects/mobile-ffmpeg/prebuilt/android-arm64/cpu-features/lib -lndk_compat' --target-os=android --enable-neon --enable-asm --enable-inline-asm --enable-cross-compile --enable-pic --enable-jni --enable-optimizations --enable-swscale --enable-shared --enable-v4l2-m2m --disable-outdev=fbdev --disable-indev=fbdev --enable-small --disable-openssl --disable-xmm-clobber-test --disable-debug --enable-lto --disable-neon-clobber-test --disable-programs --disable-postproc --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --disable-static --disable-sndio --disable-schannel --disable-securetransport --disable-xlib --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --disable-videotoolbox --disable-audiotoolbox --disable-appkit --disable-alsa --disable-cuda --disable-cuvid --disable-nvenc --disable-vaapi --disable-vdpau --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-gmp --enable-gnutls --enable-libmp3lame --enable-libass --enable-iconv --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxml2 --enable-libopencore-amrnb --enable-libshine --enable-libspeex --enable-libwavpack --enable-libkvazaar --enable-libilbc --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libaom --enable-libtwolame --disable-sdl2 --enable-libvo-amrwbenc --enable-zlib --enable-mediacodec
      libavutil      56. 55.100 / 56. 55.100
      libavcodec     58. 96.100 / 58. 96.100
      libavformat    58. 48.100 / 58. 48.100
      libavdevice    58. 11.101 / 58. 11.101
      libavfilter     7. 87.100 /  7. 87.100
      libswscale      5.  8.100 /  5.  8.100
      libswresample   3.  8.100 /  3.  8.100
    Input #0, image2, from '/storage/emulated/0/DCIM/Camera/20210713_154357.jpg':
      Duration: 00:00:00.04, start: 0.000000, bitrate: 483957 kb/s
        Stream #0:0: Video: mjpeg, yuvj420p(pc, bt470bg/unknown/unknown), 4608x3456 [SAR 59:59 DAR 4:3], 25 fps, 25 tbr, 25 tbn, 25 tbc
    Input #1, mov,mp4,m4a,3gp,3g2,mj2, from '/storage/emulated/0/MP4_20210715_093813.mp4':
      Metadata:
        major_brand     : iso6
        minor_version   : 1
        compatible_brands: mp42iso6avc1isom
        creation_time   : 2021-07-15T04:08:13.000000Z
      Duration: 00:00:19.00, start: 0.000000, bitrate: 1681 kb/s
        Stream #1:0(und): Video: h264 (avc1 / 0x31637661), yuv420p(tv, bt709), 480x848, 1615 kb/s, 30 fps, 30 tbr, 600 tbn, 1200 tbc (default)
        Stream #1:1(und): Audio: aac (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 63 kb/s (default)
    Input #2, lavfi, from 'anullsrc':
      Duration: N/A, start: 0.000000, bitrate: 705 kb/s
        Stream #2:0: Audio: pcm_u8, 44100 Hz, stereo, u8, 705 kb/s
    Codec AVOption preset (Configuration preset) specified for output file #0 (/storage/emulated/0/Android/data/com.simform.videoimageeditor/files/Output/Output1626327863.mp4) has not been used for any stream. The most likely reason is either wrong type (e.g. a video option with no video streams) or that it is a private option of some encoder which was not actually used for any stream.
    Stream mapping:
      Stream #0:0 (mjpeg) -> scale
      Stream #1:0 (h264) -> scale
      Stream #1:1 (aac) -> concat:in1:a0
      Stream #2:0 (pcm_u8) -> concat:in0:a0
      concat:out:v0 -> Stream #0:0 (mpeg4)
      concat:out:a0 -> Stream #0:1 (aac)
    Press [q] to stop, [?] for help
2021-07-15 11:14:23.477 27165-27304/com.simform.videoimageeditor I/mobile-ffmpeg: [graph 0 input from stream 0:0 @ 0x7affd0ac00] sws_param option is deprecated and ignored
    [graph 0 input from stream 1:0 @ 0x7affd0ad80] sws_param option is deprecated and ignored
    [swscaler @ 0x7addbf1000] deprecated pixel format used, make sure you did set range correctly
    [mp4 @ 0x7af2941600] Frame rate very high for a muxer not efficiently supporting it.
    Please consider specifying a lower framerate, a different muxer or -vsync 2
    [mpeg4 @ 0x7af239ad00] timebase 1/1000000 not supported by MPEG 4 standard, the maximum admitted value for the timebase denominator is 65535
    Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
    Conversion failed!
2021-07-15 11:14:23.498 7073-7073/? I/SKBD: and isTosAccept false
2021-07-15 11:14:23.579 6727-6983/? D/SDHMS:s: SIOP:: AP:309(389,90) BAT:354(354,0) CHG:385(385,0) USB:0(0,0) WIFI:303(359,50) ATC:0(0,-999) 
2021-07-15 11:14:23.672 5478-12965/? D/WifiPermissionsUtil: canAccessScanResults: pkgName = com.sec.android.sdhms, uid = 1000
2021-07-15 11:14:23.698 7073-7073/? I/SKBD: and isTosAccept false

**Comment by Nirashu** [comment]
Note : Don't create a new issue please add it in same thread, It is very difficult to handle :).

**Please check it in your logs**
deprecated pixel format used, make sure you did set range correctly
[mp4 @ 0x7af2941600] Frame rate very high for a muxer not efficiently supporting it.
Please consider specifying a lower framerate, a different muxer or -vsync 2
