### ISSUE TITLE
I can't use my query

### ISSUE THREAD

**Issue by dmitriy-kip** [SimformSolutionsPvtLtd/SSffmpegVideoOperation#20]
I want to increase the pitch of the audio and am writing my request for this. Like this: 

fun changePitchAudio(inputAudio: String, rate: Double, pitch: Double, output: String): Array<String> {
    val inputs: ArrayList<String> = ArrayList()
    inputs.apply {
        add("-i")
        add(inputAudio)
        add("-filter:a")
        add("asetrate=${rate * pitch}")
        add("-filter:a")
        add("aresample=$rate")
        add("-filter:a")
        add("atempo=${1 / pitch}")
        add("-vn")
        add("-preset")
        add("ultrafast")
        add(output)
    }
    return inputs.toArray(arrayOfNulls<String>(inputs.size))
}

but it not working. Please point me where I am wrong

**Comment by ShwetaChauhan18** [comment]
@dmitriy-kip : We will check ASAP and get back to you.

**Comment by dmitriy-kip** [comment]
@ShwetaChauhan18 Thanks

**Comment by milapchokshi-simformsolutions** [comment]
@dmitriy-kip 
that depends on many different things for example checking existing rate and pinch.
one thing i notice that you are passing rate as **double** but it should have as **Int**
sample query:
```
fun changePitchAudio(inputAudio: String, rate: Int, pitch: Double, output: String):
            Array<String> {
        val inputs: ArrayList<String> = ArrayList()
        inputs.apply {
            add("-i")
            add(inputAudio)
            add("-filter:a")
            add("asetrate=${rate * pitch}")
            add("-filter:a")
            add("aresample=$rate")
            add("-filter:a")
            add("atempo=${1 / pitch}")
            add("-vn")
            add("-preset")
            add("ultrafast")
            add(output)
        }
        return inputs.toArray(arrayOfNulls(inputs.size))
    }
```

Sample params would be:
`ffmpegQueryExtension.changePitchAudio(inputAudio, rate = 22050,pitch = 0.1, outputPath)`

let us know if you have any doubts

**Comment by shwetachauhan-simform** [comment]
@dmitriy-kip : Please lets us know if you still face any issue.

**Comment by dmitriy-kip** [comment]
It's doesn't work exactly as I expected, but thanks anyway
