### ISSUE TITLE
Error with convert image to video

### ISSUE THREAD

**Issue by minhpdn** [SimformSolutionsPvtLtd/SSffmpegVideoOperation#21]
Please check combine Images to Video and Combine Images and Videos too

**To Reproduce**
1. Go to 'Convert Image To Video'
2. Select 1 image and input 1 to the edittext
3. Create button click

Error : create file failed or not? 

**Screenshots**
![image](https://user-images.githubusercontent.com/13447967/127683885-39026ebb-7c0a-4c11-8910-a3a5b6ca799b.png)

**Desktop (please complete the following information):**
 - OS: Android 10

**Smartphone (please complete the following information):**
 - Device xiaomi readmi note 9

**Comment by ShwetaChauhan18** [comment]
@minhpdn : We will check it ASAP and get back to you

**Comment by PatelMilan** [comment]
how to filter green screen video and overlay into image

**Comment by PatelMilan** [comment]
how to filter green screen video and overlay video into the image

**Comment by milapchokshi-simformsolutions** [comment]
@minhpdn you won't be able to run this in 21, because FFMPEG lib which we have gave support to min SDK 24

**Comment by kalasaceo** [comment]
the error in picture to video is due to large size of your pics.either compress the pics you selected or use smaller pics usually <100kb would work

**Comment by sammi06** [comment]
Please tell how to Change metadata of any Audio or any video file (Title, Artist, Genre, Album) using ffmpeg.. Any Commad please. Its Urgent need help

**Comment by milapchokshi-simformsolutions** [comment]
@sammi06  Please create new request for individual queries so that if another developer have same issue then they can get solution
