### ISSUE TITLE
not compatiable with app minsdkversion = 21

### ISSUE THREAD

**Issue by shanky-gupta** [SimformSolutionsPvtLtd/SSffmpegVideoOperation#22]

**Comment by ShwetaChauhan18** [comment]
@shanky-gupta : Our demo has same minSdK version, Can you please explain more what issue you are facing??

**Comment by shanky-gupta** [comment]
When I use SSffmpegVideoOperation library in my project it gives the error :-

manifest merger failed with multiple errors see 

Then I changed our app minDkVersion 21 to 24. And I found that it works.

**Comment by ShwetaChauhan18** [comment]
@shanky-gupta : Ok, let me check

**Comment by ShwetaChauhan18** [comment]
@shanky-gupta : It's working in minSdkVersion = 21

Can you please remove .gradle and .idea folder from your project directory and rebuild it with internet.

**Comment by shanky-gupta** [comment]
I removed .gradle and .idea folder and its build fine but after starting app it crashed. with following error
Error inflating class com.google.android.material.card.MaterialCardView
    Caused by: android.view.InflateException: Binary XML file line #26 in com.example/spotviewcal2: Error inflating class com.google.android.material.card.MaterialCardView


I am trying to remove following dependecy from your lib
    implementation 'com.google.android.material:material:1.2.1'

but in this case compilation error comes:-  e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:

**Comment by ShwetaChauhan18** [comment]
Can you please create fresh project in try this library??? Just for confirmation 
I think you have another dependency issue in current project
