### ISSUE TITLE
No such filter: 'boxblur'

### ISSUE THREAD

**Issue by Mathxr** [SimformSolutionsPvtLtd/SSffmpegVideoOperation#24]
I am trying to blur the entire video, I came across the 
[following.](https://gist.github.com/sjwilliams/4b23f60fc451e7e8c59e)

however it doesn't work, I get Conversion failed.

No such filter: 'boxblur'
    Error reinitializing filters!
    Failed to inject frame into filter network: Invalid argument
    
    
I did some research and came across [this](https://github.com/tanersener/mobile-ffmpeg/issues/590), so how can I use 'boxblur'.

If it can't, there is another way to blur the video.

**Comment by ShwetaChauhan18** [comment]
@Mathxr : Will check and let you know

**Comment by milapchokshi-simformsolutions** [comment]
@Mathxr  you will need a licensed Ffmpeg to use boxBlue effect and pixelate effect.
you may try with semi white transparent image overlay with exact size(Height, Width) of video but that might not be accurate.
