### ISSUE TITLE
App ui is not responing 

### ISSUE THREAD

**Issue by abhayazzure** [SimformSolutionsPvtLtd/SSffmpegVideoOperation#51]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AshvinVavaliya** [comment]
As per the comment https://github.com/SimformSolutionsPvtLtd/SSffmpegVideoOperation/issues/52#issuecomment-1569485885, I close this issue.
