### ISSUE TITLE
Compression removes Video 

### ISSUE THREAD

**Issue by fj-gruenewald** [SimformSolutionsPvtLtd/SSffmpegVideoOperation#6]
**Describe the bug**
First of all nice work with this Project I love it.
I am currently tinkering around with ffmpeg on mobile and added your Project to mine to use the easy queries.
I noticed that the compression fails some times and got outside filming a few videos to test with your App.
When you try to compress a self filmed video it removes the video while compression and only gives a a sound file.

**To Reproduce**
1. Go to Compress a Video
2. Do a Compression
3. It returns successfully
4. In Android..data..app..Output is just a sound file

**Expected behavior**
A Video File.

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy S7 Edge]
 - OS: [Android 8.0.0]

**Additional context**
no changes to the video just filmed, and a try to compress

**Comment by Nirashu** [comment]
Can you please verify extension of  compressed output file and also verify  the output on other video application like VLC, MXPlayer etc...

**Comment by fj-gruenewald** [comment]
Input file was "20210419_183953.mp4" ,  output file was "Output1618902220.mp4" 
VLC Input(H264 - MPEG-4 AVC, 3840x2160, 29,980fps)
VLC Output(MPEG-4, 3840,2160, 25,000fps)

PS: I compressed it several times in a Row today and a few could be started with VLC a few had the same issue as before.

**Comment by Nirashu** [comment]
Please use this function for create query and let me know it is working or not, if it is work then I'll update it soon.
 
fun compressor(inputVideo: String, width: Int?, height: Int?, outputVideo: String): Array<String> {
        Common.getFrameRate(inputVideo)
        val inputs: ArrayList<String> = ArrayList()
        inputs.apply {
            add("-y")
            add("-i")
            add(inputVideo)
            add("-s")
            add("${width}x${height}")
            add("-ac")
            add("2")
            add("-ar")
            add("22050")
            add("-preset")
            add("ultrafast")
            add(outputVideo)
        }
        return inputs.toArray(arrayOfNulls<String>(inputs.size))
    }
