### ISSUE TITLE
How to stop running command.

### ISSUE THREAD

**Issue by pradeepdotsquares** [SimformSolutionsPvtLtd/SSffmpegVideoOperation#7]
Hello
I am using this library and working very great.
**I want to know how to stop the current running task?**

I didn't find any method to stop the current task. Please advise.

I have checked it by finishing the activity but the problem is it is not stopped and continues running.
and when i m trying to execute the new command the new command is waiting for the previous till it was not stopped.

Thanks.

**Comment by Nirashu** [comment]
Now any can cancel the FFMPEG process using **CallBackOfQuery.cancelProcess(executionId)** and **CallBackOfQuery.cancelProcess()**

**Comment by pradeepdotsquares** [comment]
Thank you for quick response.
**After upgrading this library to `1.0.4` I am getting error shown in the image.** 
pls help
![Capture](https://user-images.githubusercontent.com/83573305/122725941-23591c00-d293-11eb-8bd8-1fc72ac9757b.PNG)

**Comment by Nirashu** [comment]
Remove old .gradle and .idea and rebuild your project

**Comment by pradeepdotsquares** [comment]
Hi, I tried your above suggestion and all error gone.
But i got another error with **`CallBackOfQuery.cancelProcess()`** method.
This method not found. I am using latest version of this library.

![Capture](https://user-images.githubusercontent.com/83573305/122745632-d2ebb980-d2a6-11eb-8d20-99b137658f67.PNG)
![Capture1](https://user-images.githubusercontent.com/83573305/122745662-d97a3100-d2a6-11eb-9ed2-d3544b7a8203.PNG)

**Comment by Nirashu** [comment]
Please update it from 1.0.4 to 1.0.5 and rebuild your app with remove .gradle and .idea folder.

**Comment by shwetachauhan-simform** [comment]
@pradeepdotsquares : Let us know your issue fixed or not. Also, give us star if it's helpful to you

**Comment by pradeepdotsquares** [comment]
Thank you for your help. It is working now.
